name: Deploy
run-name: ${{ github.actor }} is building ${{ github.sha }}
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          architecture: 'x64'

      - name: Install Dependencies - Backend
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Test with pytest
        working-directory: backend
        run: |
          pip install pytest
          pytest

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16.x'

      - name: Install Dependencies - Frontend
        run: npm install
    
      - name: Test with Vitest
        run: npm run test:unit

      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: "Build and Push Image - Backend"
        working-directory: backend
        run: |
          docker build -t employeemgr/backend .
          docker tag employeemgr/backend:latest ghcr.io/saliovin/employeemgr/backend:latest
          docker push ghcr.io/saliovin/employeemgr/backend:latest

      - name: "Build and Push Image - Frontend"
        working-directory: frontend
        run: |
          docker build -t employeemgr/frontend --build-arg VITE_BASE_API_URL=${{ secrets.API_URL }} .
          docker tag employeemgr/frontend:latest ghcr.io/saliovin/employeemgr/frontend:latest
          docker push ghcr.io/saliovin/employeemgr/frontend:latest

      - name: Restarting Docker Compose Through SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: sudo docker compose pull employeemgr-backend employeemgr-frontend && sudo docker compose up -d --remove-orphans
